E-Project/Nexus/NexusCommunication/Controllers/plansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NexusCommunication.Models;

namespace NexusCommunication.Controllers
{
    public class plansController : Controller
    {
        private NexusEntities db = new NexusEntities();

        // GET: plans
        public ActionResult Index()
        {
            if (Session["admin"] != null)
            {

                return View(db.plans.ToList());
            }
            else
            {
                return RedirectToAction("LogIn","admins");
            }
        }

        // GET: plans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            plan plan = db.plans.Find(id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }

        // GET: plans/Create
        public ActionResult Create()
        {
            if (Session["admin"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("LogIn", "admins");
            }
            
        }

        // POST: plans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,security_deposit")] plan plan)
        {
            if (ModelState.IsValid)
            {
                db.plans.Add(plan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(plan);
        }

        // GET: plans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            plan plan = db.plans.Find(id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }

        // POST: plans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,security_deposit")] plan plan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(plan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(plan);
        }

        // GET: plans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            plan plan = db.plans.Find(id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }

        // POST: plans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            plan plan = db.plans.Find(id);
            db.plans.Remove(plan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E-Project/Nexus/NexusCommunication/Controllers/salesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NexusCommunication.Models;

namespace NexusCommunication.Controllers
{
    public class salesController : Controller
    {
        private NexusEntities db = new NexusEntities();

        // GET: sales
        public ActionResult Index()
        {
            if (Session["admin"] != null)
            {
                var sales = db.sales.Include(s => s.customer);
                return View(sales.ToList());
            }
            else
            {
                return RedirectToAction("LogIn", "admins");
            }
            
        }

        // GET: sales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sale sale = db.sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // GET: sales/Create
        public ActionResult Create()
        {
            if (Session["admin"] != null)
            {
                ViewBag.customer_id = new SelectList(db.customers, "id", "name");
                return View();
            }
            else
            {
                return RedirectToAction("LogIn", "admins");
            }
            
        }

        // POST: sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,customer_id,product_id,price,quantity,total")] sale sale)
        {
            if (ModelState.IsValid)
            {
                db.sales.Add(sale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.customer_id = new SelectList(db.customers, "id", "name", sale.customer_id);
            return View(sale);
        }

        // GET: sales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sale sale = db.sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            ViewBag.customer_id = new SelectList(db.customers, "id", "name", sale.customer_id);
            return View(sale);
        }

        // POST: sales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,customer_id,product_id,price,quantity,total")] sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.customer_id = new SelectList(db.customers, "id", "name", sale.customer_id);
            return View(sale);
        }

        // GET: sales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sale sale = db.sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            sale sale = db.sales.Find(id);
            db.sales.Remove(sale);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E-Project/Nexus/NexusCommunication/Views/Shared/_Admin Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Nexus Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Content/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/Content/assets/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Content/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/Content/assets/vendors/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/Content/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/Content/assets/images/favicon.png" />
    <style>
        
    </style>
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" id="head" href="@Url.Action("portal", "admins")">Admin Dashboard</a>
              
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-menu"></span>
                </button>

                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                            <div class="nav-profile-img">
                                <img src="~/Content/assets/images/faces/face29.jpg" alt="image">
                            </div>
                            <div class="nav-profile-text">
                                <p class="mb-1 text-black">@Session["admin"]</p>
                            </div>
                        </a>
                        <div class="dropdown-menu navbar-dropdown dropdown-menu-right p-0 border-0 font-size-sm" aria-labelledby="profileDropdown" data-x-placement="bottom-end">
                            <div class="p-3 text-center bg-primary">
                                <img class="img-avatar img-avatar48 img-avatar-thumb" src="~/Content/assets/images/faces/face29.jpg" alt="">
                            </div>
                            <div class="p-2">
                                <h5 class="dropdown-header text-uppercase pl-2 text-dark">User Options</h5>
                                <a class="dropdown-item py-1 d-flex align-items-center justify-content-between" href="#">
                                    <span>Profile</span>
                                    <span class="p-0">
                                        <span class="badge badge-success">1</span>
                                        <i class="mdi mdi-account-outline ml-1"></i>
                                    </span>
                                </a>

                                <div role="separator" class="dropdown-divider"></div>
                                <h5 class="dropdown-header text-uppercase  pl-2 text-dark mt-2">Actions</h5>

                                <a class="dropdown-item py-1 d-flex align-items-center justify-content-between" href="@Url.Action("LogOut", "admins")">
                                    <span>Log Out</span>
                                    <i class="mdi mdi-logout ml-1"></i>
                                </a>
                            </div>
                        </div>
                    </li>

                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-category">Main</li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("portal", "admins")">
                            <span class="icon-bg"><i class="mdi mdi-cube menu-icon"></i></span>
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "admins")">
                            <span class="icon-bg"><i class="fas fa-user-crown menu-icon"></i></span>
                            <span class="menu-title">Admin</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "customers")">
                            <span class="icon-bg"><i class="fas fa-users menu-icon "></i></span>
                            <span class="menu-title">Customers</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "employees")">
                            <span class="icon-bg"><i class="fas fa-user-tie menu-icon"></i></span>
                            <span class="menu-title">Employees</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                            <span class="icon-bg"><i class="fas fa-globe menu-icon"></i></span>
                            <span class="menu-title">Plans</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-basic">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "plans")">Main Plans</a></li>
                                <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "hourlies")">Dial_up & Broad B(Limited)</a></li>
                                <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "unlimites")">Dial_up & Broad B(unlimited)</a></li>
                                <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "planbs")">Landline Plan</a></li>
                                <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "planbbs")">LandLine (1)</a></li>
                            </ul>
                        </div>
                    </li>
                    @*<li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "plans")">
                            <span class="icon-bg"><i class="mdi mdi-lock menu-icon"></i></span>
                            <span class="menu-title">Plans</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "hourlies")">
                            <span class="icon-bg"><i class="fas fa-wifi menu-icon"></i></span>
                            <span class="menu-title">Dial_up & Broad B(Limited)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "unlimites")">
                            <span class="icon-bg"><i class="mdi mdi-lock menu-icon"></i></span>
                            <span class="menu-title">Dial_up & Broad B(unlimited)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "planbs")">
                            <span class="icon-bg"><i class="mdi mdi-lock menu-icon"></i></span>
                            <span class="menu-title">Landline Plan</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "planbbs")">
                            <span class="icon-bg"><i class="fas fa-phone-square-alt menu-icon"></i></span>
                            <span class="menu-title">LandLine (1)</span>
                        </a>
                    </li>*@
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "vendors")">
                            <span class="icon-bg"><i class="fas fa-inventory menu-icon"></i></span>
                            <span class="menu-title">Vendors</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "stores")">
                            <span class="icon-bg"><i class="fas fa-store menu-icon"></i></span>
                            <span class="menu-title">Stores</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "products")">
                            <span class="icon-bg"><i class="fas fa-tags menu-icon"></i></span>
                            <span class="menu-title">Products</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "sales")">
                            <span class="icon-bg"><i class="fas fa-dollar-sign menu-icon"></i></span>
                            <span class="menu-title">Sales</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "orders")">
                            <span class="icon-bg"><i class="fas fa-cart-arrow-down menu-icon"></i></span>
                            <span class="menu-title">Orders</span>
                        </a>
                    </li>
                    <li class="nav-item sidebar-user-actions">
                        <div class="sidebar-user-menu">
                            <a  class="nav-link" href="@Url.Action("LogOut", "admins")">
                                <i class="mdi mdi-logout menu-icon"></i>
                                <span class="menu-title">Log Out</span>
                            </a>
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- NAVBAR ENDED
        ================================================= -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                    <!-- partial:partials/_footer.html -->
                    <footer class="footer">
                        <div class="footer-inner-wraper">
                            <p class="footer-copy ">
                                &copy; Copyright <span class="current-year">NEXUS SERVICE MARKETING SYSTEM</span> All rights reserved.
                            </p>
                        </div>
                    </footer>
                    <!-- partial -->
                </div>
                <!-- main-panel ends -->
            </div>
            <!-- page-body-wrapper ends -->
        </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/Content/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/Content/assets/vendors/chart.js/Chart.min.js"></script>
    <script src="~/Content/assets/vendors/jquery-circle-progress/js/circle-progress.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/Content/assets/js/off-canvas.js"></script>
    <script src="~/Content/assets/js/hoverable-collapse.js"></script>
    <script src="~/Content/assets/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/Content/assets/js/dashboard.js"></script>
    <!-- End custom js for this page -->
</body>
</html>

E-Project/Nexus/NexusCommunication/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>